apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: e-ecommerce
  template:
    metadata:
      labels:
        app: e-ecommerce
    spec:
      containers:
      - name: e-ecommerce
        image: vasanth4747/ecommerce:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: e-ecommerce-service
spec:
  type: NodePort
  selector:
    app: e-ecommerce
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
